// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_NyQ1mMX4TDIGm2pt1aj-IyOOJP6pxE0',
    appId: '1:731530209807:web:2c087531b8e7959d1e917a',
    messagingSenderId: '731530209807',
    projectId: 'chat-app-2498c',
    authDomain: 'chat-app-2498c.firebaseapp.com',
    storageBucket: 'chat-app-2498c.firebasestorage.app',
    measurementId: 'G-KFTVF49LJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcj5VSQyFfe5W9r39ofQDdNEPYpjD8CU',
    appId: '1:731530209807:android:125e903493c414bb1e917a',
    messagingSenderId: '731530209807',
    projectId: 'chat-app-2498c',
    storageBucket: 'chat-app-2498c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFG4OHVpFqpd5s-YagOiFdgQi5xRFdAks',
    appId: '1:731530209807:ios:108a9e693f9bee691e917a',
    messagingSenderId: '731530209807',
    projectId: 'chat-app-2498c',
    storageBucket: 'chat-app-2498c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFG4OHVpFqpd5s-YagOiFdgQi5xRFdAks',
    appId: '1:731530209807:ios:108a9e693f9bee691e917a',
    messagingSenderId: '731530209807',
    projectId: 'chat-app-2498c',
    storageBucket: 'chat-app-2498c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_NyQ1mMX4TDIGm2pt1aj-IyOOJP6pxE0',
    appId: '1:731530209807:web:6288cf7d5724e83f1e917a',
    messagingSenderId: '731530209807',
    projectId: 'chat-app-2498c',
    authDomain: 'chat-app-2498c.firebaseapp.com',
    storageBucket: 'chat-app-2498c.firebasestorage.app',
    measurementId: 'G-TKBDHBE3XN',
  );
}
